# Generated by Django 3.2 on 2023-03-20 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_platform.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='模块名称')),
                ('test_owner', models.CharField(max_length=20, verbose_name='测试负责人')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块信息表',
                'verbose_name_plural': '模块信息表',
                'db_table': 'atp_module',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名称')),
                ('proj_owner', models.CharField(max_length=20, verbose_name='项目负责人')),
                ('test_owner', models.CharField(max_length=20, verbose_name='测试负责人')),
                ('dev_owner', models.CharField(max_length=20, verbose_name='开发负责人')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='项目更新时间')),
            ],
            options={
                'verbose_name': '项目信息表',
                'verbose_name_plural': '项目信息表',
                'db_table': 'atp_project',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env', models.CharField(default='', max_length=50, verbose_name='环境')),
                ('ip', models.CharField(default='', max_length=50, verbose_name='IP地址')),
                ('port', models.CharField(default='', max_length=50, verbose_name='端口号')),
                ('remark', models.CharField(max_length=256, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '环境配置表',
                'verbose_name_plural': '环境配置表',
                'db_table': 'atp_server',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('request_data', models.CharField(default='', max_length=1024, verbose_name='请求数据')),
                ('uri', models.CharField(default='', max_length=1024, verbose_name='接口地址')),
                ('assert_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='断言内容')),
                ('maintainer', models.CharField(default='', max_length=20, verbose_name='编写人员')),
                ('extract_var', models.CharField(blank=True, max_length=1024, null=True, verbose_name='提取变量表达式')),
                ('request_method', models.CharField(max_length=128, null=True, verbose_name='请求方式')),
                ('status', models.IntegerField(help_text='0:表示有效，1:表示无效，用于软删除', null=True)),
                ('related_case_id', models.IntegerField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_module', smart_selects.db_fields.GroupedForeignKey(group_field='belong_project', on_delete=django.db.models.deletion.CASCADE, to='main_platform.module', verbose_name='所属模块')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
                'db_table': 'atp_test_case',
            },
        ),
        migrations.CreateModel(
            name='TestExecute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('user', models.CharField(max_length=128, null=True)),
                ('type', models.IntegerField(default=0)),
                ('case_or_suite_ids', models.CharField(max_length=1024)),
                ('download_report_path', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': '执行结果记录表',
                'verbose_name_plural': '执行结果记录表',
                'db_table': 'atp_test_execute',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suite_desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='用例集合描述')),
                ('if_execute', models.IntegerField(default=0, help_text='0：执行；1：不执行', verbose_name='是否执行')),
                ('test_case_model', models.CharField(blank=True, help_text='data/keyword', max_length=128, null=True, verbose_name='测试执行模式')),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用例集合表',
                'verbose_name_plural': '用例集合表',
                'db_table': 'atp_test_suite',
            },
        ),
        migrations.CreateModel(
            name='UpLoadsCaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ImageField(upload_to=main_platform.models.uploads_file)),
                ('uptimes', models.CharField(blank=True, max_length=128, null=True, verbose_name='上传时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'atp_uploads_case_template',
            },
        ),
        migrations.CreateModel(
            name='TestSuiteTestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_suite', models.CharField(max_length=128)),
                ('status', models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True)),
                ('exception_info', models.CharField(blank=True, max_length=2048, null=True)),
                ('request_data', models.CharField(max_length=1024, null=True, verbose_name='请求数据')),
                ('response_data', models.CharField(max_length=1024, null=True, verbose_name='响应数据')),
                ('execute_result', models.CharField(max_length=1024, null=True, verbose_name='执行结果')),
                ('extract_var', models.CharField(max_length=1024, null=True, verbose_name='提取变量')),
                ('execute_total_time', models.CharField(max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '集合执行里的用例记录表',
                'verbose_name_plural': '集合执行里的用例记录表',
                'db_table': 'atp_test_suite_test_case_execute_record',
            },
        ),
        migrations.CreateModel(
            name='TestSuiteExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_execute', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('execute_total_time', models.CharField(max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testsuite', verbose_name='测试集合')),
            ],
            options={
                'verbose_name': '集合执行结果记录表',
                'verbose_name_plural': '集合执行结果记录表',
                'db_table': 'atp_test_suite_execute_record',
            },
        ),
        migrations.CreateModel(
            name='TestCaseExecuteResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_execute', models.CharField(max_length=128)),
                ('status', models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True)),
                ('exception_info', models.CharField(blank=True, max_length=2048, null=True)),
                ('request_data', models.CharField(max_length=1024, null=True, verbose_name='请求数据')),
                ('response_data', models.CharField(max_length=1024, null=True, verbose_name='响应数据')),
                ('execute_result', models.CharField(max_length=1024, null=True, verbose_name='执行结果')),
                ('extract_var', models.CharField(max_length=1024, null=True, verbose_name='提取变量')),
                ('execute_total_time', models.CharField(max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例执行结果记录表',
                'verbose_name_plural': '用例执行结果记录表',
                'db_table': 'atp_test_case_execute_result',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.project'),
        ),
        migrations.CreateModel(
            name='AddCaseIntoSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0, help_text='0：有效，1：无效', verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testcase', verbose_name='测试用例')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testsuite', verbose_name='用例集合')),
            ],
            options={
                'verbose_name': '用例集中添加用例表',
                'verbose_name_plural': '用例集中添加用例表',
                'db_table': 'atp_add_case_into_suite',
            },
        ),
    ]
