# Generated by Django 3.2 on 2023-03-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitetestcaseexecuterecord',
            name='belong_test_case',
        ),
        migrations.DeleteModel(
            name='TestSuiteExecuteRecord',
        ),
        migrations.DeleteModel(
            name='TestSuiteTestCaseExecuteRecord',
        ),
    ]
