# Generated by Django 3.2 on 2023-03-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0002_auto_20230320_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteTestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_suite', models.CharField(max_length=128)),
                ('status', models.IntegerField(help_text='0：表示未执行，1：表示已执行', null=True)),
                ('exception_info', models.CharField(blank=True, max_length=2048, null=True)),
                ('request_data', models.CharField(max_length=1024, null=True, verbose_name='请求数据')),
                ('response_data', models.CharField(max_length=1024, null=True, verbose_name='响应数据')),
                ('execute_result', models.CharField(max_length=1024, null=True, verbose_name='执行结果')),
                ('extract_var', models.CharField(max_length=1024, null=True, verbose_name='提取变量')),
                ('execute_total_time', models.CharField(max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('belong_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '集合执行里的用例记录表',
                'verbose_name_plural': '集合执行里的用例记录表',
                'db_table': 'atp_test_suite_test_case_execute_record',
            },
        ),
        migrations.CreateModel(
            name='TestSuiteExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belong_test_execute', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('execute_total_time', models.CharField(max_length=300, null=True, verbose_name='执行总计耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.testsuite', verbose_name='测试集合')),
            ],
            options={
                'verbose_name': '集合执行结果记录表',
                'verbose_name_plural': '集合执行结果记录表',
                'db_table': 'atp_test_suite_execute_record',
            },
        ),
    ]
