# Generated by Django 3.2 on 2023-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_testsuiteexecuterecord_testsuitetestcaseexecuterecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='if_execute',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='test_case_model',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='status',
            field=models.IntegerField(help_text='0:表示有效，1:表示无效，用于软删除', null=True),
        ),
    ]
