# Generated by Django 3.2 on 2023-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0004_auto_20230322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.IntegerField(default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='status',
            field=models.IntegerField(default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True),
        ),
    ]
