# Generated by Django 3.2 on 2023-03-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0005_auto_20230322_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuiteexecuterecord',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='testsuiteexecuterecord',
            name='execute_end_time',
        ),
        migrations.RemoveField(
            model_name='testsuiteexecuterecord',
            name='execute_start_time',
        ),
        migrations.RemoveField(
            model_name='testsuiteexecuterecord',
            name='execute_total_time',
        ),
        migrations.RemoveField(
            model_name='testsuiteexecuterecord',
            name='updated_time',
        ),
    ]
