# Generated by Django 3.2 on 2023-03-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0006_auto_20230325_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuitetestcaseexecuterecord',
            old_name='belong_test_suite',
            new_name='belong_test_suite_exe',
        ),
    ]
