# Generated by Django 3.2 on 2023-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0007_rename_belong_test_suite_testsuitetestcaseexecuterecord_belong_test_suite_exe'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecuted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=128, verbose_name='任务id')),
                ('status', models.IntegerField(default='done', null=True, verbose_name='任务状态')),
                ('run_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('user', models.CharField(max_length=64, verbose_name='任务负责人')),
            ],
        ),
    ]
