# Generated by Django 3.2 on 2023-04-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0008_jobexecuted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexecuted',
            options={'verbose_name': '定时任务表', 'verbose_name_plural': '定时任务表'},
        ),
        migrations.AlterModelTable(
            name='jobexecuted',
            table='atp_jobexecuted',
        ),
    ]
