# Generated by Django 3.2 on 2023-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0009_auto_20230427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecuted',
            name='status',
            field=models.CharField(default='done', max_length=64, null=True, verbose_name='任务状态'),
        ),
    ]
