# Generated by Django 3.2 on 2023-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0011_alter_jobexecuted_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecuted',
            name='job_id',
            field=models.CharField(max_length=128, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='jobexecuted',
            name='status',
            field=models.IntegerField(default=0, help_text='0为未开始，1为已完成，2为删除，3为暂停', verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='jobexecuted',
            name='user',
            field=models.CharField(max_length=64, verbose_name='负责人'),
        ),
    ]
