# Generated by Django 3.2 on 2023-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0012_auto_20230501_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecute',
            name='job_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
