# Generated by Django 3.2 on 2023-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0013_testexecute_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='多个收件人使用英文;来分隔', max_length=256, null=True, verbose_name='收件人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告收件人表',
                'verbose_name_plural': '报告收件人表',
                'db_table': 'atp_email_address',
            },
        ),
    ]
