# Generated by Django 3.2 on 2023-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0014_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='realm_name',
            field=models.IntegerField(default=0, help_text='0：否，1：是', verbose_name='是否为域名'),
        ),
    ]
