# Generated by Django 3.2 on 2023-05-20 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_platform.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_platform', '0016_auto_20230520_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcaseintosuite',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0：有效，1：无效', null=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='address',
            field=models.CharField(blank=True, help_text='多个收件人使用英文;来分隔', max_length=256, null=True, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='jobexecuted',
            name='job_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='jobexecuted',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0为未开始，1为已完成，2为删除，3为暂停', null=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='jobexecuted',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='module',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='简要描述'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='module',
            name='test_owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dev_owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='开发负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='server',
            name='env',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='realm_name',
            field=models.IntegerField(blank=True, default=0, help_text='0：否，1：是', null=True, verbose_name='请求方式为Https'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='maintainer',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='编写人员'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='request_data',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='request_method',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='接口地址'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='belong_test_execute',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='execute_result',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='execute_total_time',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='执行总计耗时'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='extract_var',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='提取变量'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='request_data',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='response_data',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='status',
            field=models.IntegerField(blank=True, help_text='0：表示未执行，1：表示已执行', null=True),
        ),
        migrations.AlterField(
            model_name='testexecute',
            name='case_or_suite_ids',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='testexecute',
            name='download_report_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='testexecute',
            name='job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testexecute',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testexecute',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='status',
            field=models.IntegerField(blank=True, default=0, help_text='0:表示有效，1:表示无效，用于软删除', null=True),
        ),
        migrations.AlterField(
            model_name='testsuiteexecuterecord',
            name='belong_test_execute',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testsuiteexecuterecord',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='belong_test_suite_exe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='execute_result',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='execute_total_time',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='执行总计耗时'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='extract_var',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='提取变量'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='request_data',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='response_data',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='testsuitetestcaseexecuterecord',
            name='status',
            field=models.IntegerField(blank=True, help_text='0：表示未执行，1：表示已执行', null=True),
        ),
        migrations.AlterField(
            model_name='uploadscasetemplate',
            name='address',
            field=models.ImageField(blank=True, null=True, upload_to=main_platform.models.uploads_file),
        ),
        migrations.AlterField(
            model_name='uploadscasetemplate',
            name='owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
